blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='home'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sendmail.urls', namespace='sendmail')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import UserLogoutView, UserLoginView, RegisterView, verification, UserUpdateView, get_users_list

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('verify_message/', TemplateView.as_view(template_name='users/verify_message.html'), name='verify_message'),
    path('email/verify/<str:verify_code>', verification, name='verify'),
    path('success_verify/', TemplateView.as_view(template_name='users/success_verify.html'), name='success_verify'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify'),
    path('users_list/', get_users_list, name='list_view'),
    path('edit/<int:pk>', UserUpdateView.as_view(), name='edit')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from blog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    is_active = models.BooleanField(default=True, verbose_name='Активный')
    verify_code = models.CharField(max_length=12, verbose_name='код верификации', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            ('set_is_active', 'Может блокировать пользователя')
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class ModeratorForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import CreateView, UpdateView
from users.forms import RegisterForm, ModeratorForm
from users.models import User
from django.utils.crypto import get_random_string


class UserLoginView(LoginView):
    template_name = 'users/login.html'


class UserLogoutView(LogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        self.object = form.save()
        self.object.is_active = False
        self.object.verify_code = get_random_string(12)
        self.object.save()
        url = f'http://127.0.0.1:8000/users/email/verify/{self.object.verify_code}'
        send_mail(
                subject='Регистрация',
                message=f'Для успешной регистрации перейдите по ссылке: {url}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email],
                fail_silently=False,
            )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('users:verify_message')


def verification(request, verify_code):
    try:
        user = User.objects.filter(verify_code=verify_code).first()
        user.is_active = True
        user.save()
        return redirect('users:success_verify')
    except (AttributeError, ValidationError):
        return redirect('users:invalid_verify')


class UserUpdateView(PermissionRequiredMixin, UpdateView):
    model = User
    form_class = ModeratorForm
    permission_required = 'set_is_active'
    success_url = 'users:users_list'

    def get_success_url(self):
        return reverse('users:list_view')


@login_required
@permission_required(['users.view_user', 'users.set_is_active'])
def get_users_list(request):
    users_list = User.objects.all()
    context = {
        'object_list': users_list,
        'title': 'Список пользователей сервиса',
    }
    return render(request, 'users/users_list.html', context)

users/templates/users/login.html
{% extends 'sendmail/base.html' %}
{% block content %}
    <div class="col-12">
        <form class="form-signin" method="post">
            {% csrf_token %}
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="card-body">
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>

                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'sendmail/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/success_verify.html
{% extends 'sendmail/base.html' %}

{% block content %}
<div class="row text-center">
    <div class="col-12">
        <h3>
            Поздравляем, Вы успешно зарегистрировались!<br>
            Для дальнейшей работы нажмите "Войти".
        </h3>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'sendmail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'sendmail/base.html' %}
{% block content %}
    <div class="header mx-auto text-center">
        <h5 class="display-4">{{ title }}</h5>
    </div>
    <div class="col-12">
        <div class="row mb-3">
            {% for object in object_list %}
                <div class="col-6 mb-3">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="my-0 font-weight-normal mb-3">Пользователь: {{ object.email }}</h3>
                            {% if not object.is_active %}
                                <p>Заблокирован</p>
                            {% else %}
                                <p>Активный</p>
                            {% endif %}
                            <a class="p-2 btn btn-outline-primary" href="{% url 'users:edit' object.pk %}">Редактировать</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

users/templates/users/verify_message.html
{% extends 'sendmail/base.html' %}

{% block content %}
    <div class="row text-center">
        <div class="col-12">
            <h3>На почту, указанную при регистрации направлена ссылка.<br>
                Пожалуйста, перейдите по ней, чтобы завершить регистрацию.
            </h3>
        </div>
    </div>
{% endblock %}