blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='home'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sendmail.urls', namespace='sendmail')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sendmail/urls.py
from django.urls import path

from sendmail.apps import SendmailConfig
from sendmail.views import MessageListView, MessageCreateView, MessageUpdateView, \
    MessageDetailView, MessageDeleteView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingListView, \
    MailingDetailView, ClientListView, ClientCreateView, ClientUpdateView, MailingUpdateModeratorView, \
    HomeView

app_name = SendmailConfig.name


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('mailing_list', MailingListView.as_view(), name='mailing_list'),
    path('mailing_add/', MailingCreateView.as_view(), name='mailing_add'),
    path('mailing_view/<int:pk>', MailingDetailView.as_view(), name='mailing_view'),
    path('mailing_edit/<int:pk>/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailing_mod_edit/<int:pk>/', MailingUpdateModeratorView.as_view(), name='mailing_mod_edit'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_add/', MessageCreateView.as_view(), name='message_add'),
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('message_view/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('client_add/', ClientCreateView.as_view(), name='client_add'),
    path('client_edit/<int:pk>', ClientUpdateView.as_view(), name='client_edit'),
]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import UserLogoutView, UserLoginView, RegisterView, verification, UserUpdateView, get_users_list

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('verify_message/', TemplateView.as_view(template_name='users/verify_message.html'), name='verify_message'),
    path('email/verify/<str:verify_code>', verification, name='verify'),
    path('success_verify/', TemplateView.as_view(template_name='users/success_verify.html'), name='success_verify'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify'),
    path('users_list/', get_users_list, name='list_view'),
    path('edit/<int:pk>', UserUpdateView.as_view(), name='edit')
]

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='заголовок')
    content = models.TextField(verbose_name='текст')
    preview = models.ImageField(upload_to='blog/preview/', verbose_name='изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='количетсво просмотров')
    public_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    def __repr__(self):
        return self.title

sendmail/models.py
from django.db import models
from django.utils import timezone

from blog.models import NULLABLE

import users.models

STATUS_CHOICES = [
    ('Создана', 'Создана'),
    ('Запущена', 'Запушена'),
    ('Завершена', 'Завершена'),
]

INTERVAL_CHOICES = [
    ('Разовая', 'Разовая'),
    ('Ежедневно', 'Ежедневно'),
    ('Раз в неделю', 'Раз в неделю'),
    ('Раз в месяц', 'Раз в месяц')
]


class Client(models.Model):
    full_name = models.CharField(max_length=125, verbose_name='ФИО')
    email = models.EmailField(verbose_name='почта')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    owner = models.ForeignKey(users.models.User, on_delete=models.CASCADE, null=True, verbose_name='чей клиент')

    def __str__(self):
        return f'{self.email} ({self.full_name})'

    def __repr__(self):
        return f'{self.email}, ({self.full_name})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name='тема')
    content = models.TextField(verbose_name='содержимое')

    owner = models.ForeignKey(users.models.User, on_delete=models.CASCADE, null=True, verbose_name='Владелец сообщения')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Mailing(models.Model):
    name = models.CharField(max_length=100, verbose_name='название рассылки')
    mail_to = models.ManyToManyField(Client, verbose_name='кому')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение', **NULLABLE)
    start_date = models.DateTimeField(default=timezone.now, verbose_name='время старта рассылки')
    next_date = models.DateTimeField(default=timezone.now, verbose_name='время следующей рассылки')
    end_date = models.DateTimeField(verbose_name='время окончания рассылки')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, help_text='Выберите создана или Завершена')
    interval = models.CharField(default='разовая', max_length=50, choices=INTERVAL_CHOICES,
                                verbose_name='периодичность')
    is_activated = models.BooleanField(default=True, verbose_name='действующая')
    owner = models.ForeignKey(users.models.User, on_delete=models.CASCADE, null=True, verbose_name='Владелец рассылки')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ('start_date',)
        permissions = [
            ('set_is_activated', 'Может отключать рассылку')
        ]


class Logs(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка', **NULLABLE)
    status = models.CharField(max_length=50, verbose_name='статус попытки', null=True)
    last_mailing_time = models.DateTimeField(auto_now=True, verbose_name='время последней отправки')

    def __str__(self):
        return f'Отправлено: {self.last_mailing_time}, Статус: {self.status}'

    class Meta:
        verbose_name = 'log'
        verbose_name_plural = 'logs'

sendmail/forms.py
from django import forms
from django.forms import DateTimeInput

from sendmail.models import Mailing, Message, Client


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['mail_to'].queryset = Client.objects.filter(owner=user)
        self.fields['message'].queryset = Message.objects.filter(owner=user)

    class Meta:
        model = Mailing
        exclude = ('next_date', 'owner', 'is_activated',)

        widgets = {
            'start_date': DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
        }


class MailingModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('is_activated',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)

sendmail/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from blog.models import Blog
from sendmail.forms import MailingForm, MessageForm, ClientForm, MailingModeratorForm
from sendmail.models import Message, Mailing, Client, Logs
from sendmail.services import get_cache_for_mailings, get_cache_for_active_mailings


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('sendmail:mailing_list')
    extra_context = {'title': 'Создать рассылку'}

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form, *args, **kwargs):
        if form.is_valid():
            new_mailing = form.save(commit=False)
            new_mailing.owner = self.request.user
            new_mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('sendmail:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return self.request.user == Mailing.objects.get(pk=self.kwargs['pk']).owner


class MailingUpdateModeratorView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingModeratorForm
    success_url = reverse_lazy('sendmail:mailing_list')
    permission_required = 'sendmail.set_is_activated'


class HomeView(ListView):
    model = Mailing
    template_name = 'sendmail/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailings_count'] = get_cache_for_active_mailings()
        context_data['active_mailings_count'] = get_cache_for_active_mailings()
        blog_list = list(Blog.objects.all())
        random.shuffle(blog_list)
        context_data['blog_list'] = blog_list[:3]
        context_data['clients_count'] = len(Client.objects.all())

        return context_data


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    extra_context = {'title': 'Список рассылок'}


class MailingDetailView(DetailView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['clients'] = list(self.object.mail_to.all())
        context_data['logs'] = list(Logs.objects.filter(mailing=self.object))

        return context_data


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('sendmail:mailing_list')


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('sendmail:message_list')
    extra_context = {'title': 'Создание сообщения'}

    def form_valid(self, form):
        new_message = form.save()
        new_message.owner = self.request.user
        new_message.save()

        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse('sendmail:message_view', args=[self.kwargs.get('pk')])


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {'title': 'Список сообщений'}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = Message.objects.filter(owner=self.request.user)

        return queryset


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('sendmail:message_list')


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {'title': 'Список клиентов'}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = Client.objects.filter(owner=self.request.user)

        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('sendmail:client_list')
    extra_context = {'title': 'Добавить нового клиента'}

    def form_valid(self, form):
        new_client = form.save()
        new_client.owner = self.request.user
        new_client.save()

        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('sendmail:client_list')

    def test_func(self):
        return self.request.user == Client.objects.get(pk=self.kwargs['pk']).owner

sendmail/templates/sendmail/base.html
{% load static %}
<!doctype html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SendMailService</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>

<style>
    body {
        background: url('static/images/bkg.png');
        background-position: center;
        background-attachment: fixed;
        background-size; cover;
        font-family: 'Lato', sans-serif;
    }
    .card {
background-color: rgba(255, 255, 255, 0.1);
    }
    .container {
        padding: 50px 16px;
    }
    button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
    }

    button:hover, a:hover {
        opacity: 0.7;
    }
    .title {
        color: rgba(83, 149, 189, 0.7);
        font-size: 30px;
    }
    a {
        text-decoration: none;
        font-size: 22px;
        color: black;
    }
    .topnav {
        overflow: hidden;
        background-color: #333;
    }

    .topnav a {
        float: right;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
    }

    .topnav a:hover {
        background-color: #ddd;
        color: black;
    }

    .topnav a.active {
        background-color: #4CAF50;
        color: white;
    }
.overlay {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0, 0.9);
    overflow-x: hidden;
    transition: 0.5s;
}

.overlay-content {
    position: relative;
    top: 25%;
    width: 100%;
    text-align: center;
    margin-top: 30px;
}

.overlay a {
    padding: 8px;
    text-decoration: none;
    font-size: 36px;
    color: #818181;
    display: block;
    transition: 0.3s;
}

.overlay a:hover, .overlay a:focus {
    color: #f1f1f1;
}

.overlay .closebtn {
    position: absolute;
    top: 20px;
    left: 45px;
    font-size: 60px;
}

@media screen and (max-height: 450px) {
  .overlay a {font-size: 20px}
  .overlay .closebtn {
    font-size: 40px;
    top: 15px;
    right: 35px;
  }
}

.header {
  overflow: hidden;
  background-color: rgba(255, 255, 255, 0.0);
  padding: 20px 10px;
}

.header a {
  float: left;
  color: black;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px;
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

.header a.active {
  background-color: dodgerblue;
  color: white;
  border-radius: 1px;
}
footer {
    position: left;
    bottom: 0;
    width: 100%;
    background-color: rgba(255, 255, 255, 0.0);
    padding: 0px 0;
}

</style>
<div class="header">
    <a href="{% url 'sendmail:home' %}" class="logo">SendMailService</a>

    <div class="topnav">
        <a class="active" href="{% url 'sendmail:home' %}">На главную</a>

        {% if user.is_authenticated %}
        <a class="active" href="{% url 'users:logout' %}">Выйти</a>
        <a class="text text-muted" href="#profile" >{{ user.email }}</a>
        {% else %}
        <a href="{% url 'users:login' %}">Войти</a>
        <a href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </div>
</div>

<div id="myNav" class="overlay">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    <div class="overlay-content">
        <a href="{% url 'sendmail:mailing_list' %}">Рассылки</a>
        <a href="{% url 'sendmail:message_list' %}">Сообщения</a>
        <a href="{% url 'sendmail:client_list' %}">Клиенты</a>
        {% if perms.sendmail.set_is_active %}
        <a href="{% url 'users:list_view' %}">Пользователи</a>
        {% endif %}
    </div>
</div>


<span style="font-size:30px;cursor:pointer" onclick="openNav()">☰ Открыть меню</span>

<script>
    function openNav() {
        document.getElementById("myNav").style.width = "100%";
    }

    function closeNav() {
        document.getElementById("myNav").style.width = "0%";
    }
</script>


{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SendMailService
            <small class="d-block mb-3 text-muted">&copy; 2023-{% now 'Y' %}</small>
        </div>
    </div>
</footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

sendmail/templates/sendmail/client_form.html
{% extends 'sendmail/base.html' %}

{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        {% else %}
                            <button type="submit" class="btn btn-primary">Создать</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

sendmail/templates/sendmail/client_list.html
{% extends 'sendmail/base.html' %}
{% block content %}
    <h5 class="display-4 text-center">{{ title }}</h5>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'sendmail:client_add' %}">Добавить клиента</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">{{ object.full_name|title }}</h3>
                    </div>
                    <div class="card-body">
                        <p>{{ object.email }}</p>
                        {% if object.comment %}
                            <p>{{ object.comment }}</p>
                        {% endif %}

                        <a href="{% url 'sendmail:client_edit' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

sendmail/templates/sendmail/mailing_confirm_delete.html
{% extends 'sendmail/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить рассылку "{{ object.name }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'sendmail:home' %}" class="btn btn-warning">Отмена</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sendmail/templates/sendmail/mailing_detail.html
{% extends 'sendmail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">

                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Название:</td>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <td>Тема сообщения:</td>
                            <td>{{ object.message.title }}</td>
                        </tr>
                        <tr>
                            <td>Кому:</td>
                            <td>{{ clients }}</td>
                        </tr>
                        <tr>
                            <td>Старт рассылки:</td>
                            <td>{{ object.start_date }}</td>
                        </tr>
                        <tr>
                            <td>Периодичность:</td>
                            <td>{{ object.interval }}</td>
                        </tr>
                        <tr>
                            <td>Завершение рассылки:</td>
                            <td>{{ object.end_date }}</td>
                        </tr>
                        <tr>
                            <td>Текущий статус:</td>
                            <td>{{ object.status }}</td>
                        </tr>
                    </table>

                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if perms.sendmail.set_is_activated %}
                            <a href="{% url 'sendmail:mailing_mod_edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-primary">Редактировать</a>
                        {% else %}

                            <a href="{% url 'sendmail:mailing_edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-primary">Редактировать</a>
                            <a href="{% url 'sendmail:mailing_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">

                <div class="card-body">
                    {% for log in logs %}
                        <p>{{ log }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sendmail/templates/sendmail/mailing_form.html
{% extends 'sendmail/base.html' %}

{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-6">
    <div class="card">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                            <p class="help" id="{{ field.auto_id }}_helptext">
                                {{ field.help_text|safe }}
                            </p>
                        {% endif %}
                    </div>
                {% endfor %}

                {% if object %}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                {% else %}
                <button type="submit" class="btn btn-primary">Создать</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

sendmail/templates/sendmail/mailing_list.html
{% extends 'sendmail/base.html' %}
{% block content %}
    <h5 class="display-4 text-center">{{ title }}</h5>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'sendmail:mailing_add' %}">Создать рассылку</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
            {% if user == object.owner or perms.sendmail.view_mailing %}
            <div class="col-6 mb-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">Рассылка: {{ object.name }}</h3>
                    </div>
                    <div class="card-body">
                        <p>с {{ object.start_date }} по {{ object.end_date }}</p>
                        <p>с периодичностью {{ object.interval }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'sendmail:mailing_view' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-primary my-md-5">Подробнее</a>

                        </div>
                        <div class="card-footer">
                            {% if object.is_activated %}
                            <p>Действующая</p>
                            {% else %}
                            <p>Отменена</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

sendmail/templates/sendmail/message_confirm_delete.html
{% extends 'sendmail/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить сообщение "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'sendmail:message_list' %}" class="btn btn-warning">Отмена</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sendmail/templates/sendmail/message_detail.html
{% extends 'sendmail/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <p>{{ object.content }}</p>
                    {% if user == object.owner %}
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'sendmail:message_edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Редактировать</a>
                            <a href="{% url 'sendmail:message_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sendmail/templates/sendmail/message_list.html
{% extends 'sendmail/base.html' %}
{% block content %}
    <h5 class="display-4 text-center">{{ title }}</h5>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'sendmail:message_add' %}">Создать сообщение для рассылки</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
        <div class="col-6 mb-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{ object.title }}</h3>
                </div>
                <div class="card-body">
                    <p>{{ object.content }}</p>
                    <a href="{% url 'sendmail:message_view' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">Просмотр</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}